version: "3"
services:
  rabbitmq:
    image: rabbitmq
  cli:
    build:
      dockerfile: cli.Dockerfile
      context: .
    depends_on:
      - rabbitmq
      - apigw
      - bang
      - bar
      - fib
      - foo
    environment:
      - RabbitMQ__Connection__Hostname=rabbitmq
  apigw:
    build:
      dockerfile: apigw.Dockerfile
      context: .
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Connection__Hostname=rabbitmq
  bang:
    build:
      dockerfile: bang.Dockerfile
      context: .
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Connection__Hostname=rabbitmq
  bar:
    build:
      dockerfile: bar.Dockerfile
      context: .
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Connection__Hostname=rabbitmq
  fib:
    build:
      dockerfile: fib.Dockerfile
      context: .
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Connection__Hostname=rabbitmq
  foo:
    build:
      dockerfile: foo.Dockerfile
      context: .
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Connection__Hostname=rabbitmq