version: "3"
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  apigw:
    build:
      dockerfile: apigw.Dockerfile
      context: .
    ports:
      - 59023:59023
  bang:
    build:
      dockerfile: bang.Dockerfile
      context: .
  bar:
    build:
      dockerfile: bar.Dockerfile
      context: .
  fib:
    build:
      dockerfile: fib.Dockerfile
      context: .
  foo:
    build:
      dockerfile: foo.Dockerfile
      context: .